// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvAHMF2FGZiF595LcKgJpu0ruoLG9QV90',
    appId: '1:751508670569:web:ff0fae71ce5f14dc9b7af8',
    messagingSenderId: '751508670569',
    projectId: 'news-9770c',
    authDomain: 'news-9770c.firebaseapp.com',
    storageBucket: 'news-9770c.appspot.com',
    measurementId: 'G-D8Z41E0FVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg4CwW7aLGuX0hnzx41tP_hdHwhCjwd2k',
    appId: '1:751508670569:android:0377090ea04ee9c59b7af8',
    messagingSenderId: '751508670569',
    projectId: 'news-9770c',
    storageBucket: 'news-9770c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC43VH7hqnJe5yMwucl7Vcg0_hgQnspS60',
    appId: '1:751508670569:ios:4d9e171842fb09859b7af8',
    messagingSenderId: '751508670569',
    projectId: 'news-9770c',
    storageBucket: 'news-9770c.appspot.com',
    iosClientId: '751508670569-qt0c2bm8rtqtqivhidmvji2fa70svj6i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC43VH7hqnJe5yMwucl7Vcg0_hgQnspS60',
    appId: '1:751508670569:ios:9e38dbcbc4f7bdb99b7af8',
    messagingSenderId: '751508670569',
    projectId: 'news-9770c',
    storageBucket: 'news-9770c.appspot.com',
    iosClientId: '751508670569-dmqs1hioe7ejpa2t9kkdo7ro89c1mvc6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
